### ISSUE TITLE
关于使用Autojs达到实现跑jd脚本的问题

### ISSUE THREAD

**Issue by DoveBoy** [710850609/autojs-webView#1]
@710850609 [Android使用Autojs跑jd脚本的问题](https://github.com/NobyDa/Script/issues/173)，看到大佬的截图，想问一下具体达到这个效果需要怎么做？

**Comment by YmStrip** [comment]
这个看了半天还是没分清楚注入脚本和jsbright，函数包里面的init第二个数组传递的脚本文件，里面window. Android.invoke到底有什么用，传递的对象在html里面也没有，

**Comment by YmStrip** [comment]
就想在webview loadurl的页面里面，通过这个函数包传递一些变量进去

**Comment by 710850609** [comment]
> @710850609 [Android使用Autojs跑jd脚本的问题](https://github.com/NobyDa/Script/issues/173)，看到大佬的截图，想问一下具体达到这个效果需要怎么做？


我是用webview去跑jd脚本，现在安卓机器大多webview支持es6语法。
逻辑是
1 webview登录jd，通过cookiemanager获取cookie
2 通过 webViewExpand.init(webViewWidget, jsFileList [, supportVConsole]) 注入http api支持，jd脚本
3 手动调用执行方法

**Comment by 710850609** [comment]
> 就想在webview loadurl的页面里面，通过这个函数包传递一些变量进去

这个才是在webview 执行js
callJavaScript(webViewWidget, script [, callback])

**Comment by 710850609** [comment]
> 就想在webview loadurl的页面里面，通过这个函数包传递一些变量进去

这个才是在webview 执行js
callJavaScript(webViewWidget, script [, callback])

**Comment by 710850609** [comment]
> 这个看了半天还是没分清楚注入脚本和jsbright，函数包里面的init第二个数组传递的脚本文件，里面window. Android.invoke到底有什么用，传递的对象在html里面也没有，

jsbridge 可以不需要关注，只要关注 网页调用 aj、aj调用网页

**Comment by 710850609** [comment]
> > @710850609 [Android使用Autojs跑jd脚本的问题](https://github.com/NobyDa/Script/issues/173)，看到大佬的截图，想问一下具体达到这个效果需要怎么做？
> 
> 我是用webview去跑jd脚本，现在安卓机器大多webview支持es6语法。
> 逻辑是
> 1 webview登录jd，通过cookiemanager获取cookie
> 2 通过 webViewExpand.init(webViewWidget, jsFileList [, supportVConsole]) 注入http api支持，jd脚本
> 3 手动调用执行方法


autojs pro 8.6 （内测版、收费）已经支持nodejs，有兴趣可以去试试，直接用nodejs方式运行。这种我还没试过

**Comment by DoveBoy** [comment]
@710850609 好复杂的样子，能否给个详细的操作步骤？

**Comment by 710850609** [comment]
> @710850609 好复杂的样子，能否给个详细的操作步骤？

大概思路是这样，如果你不熟悉autojs，可能还不如用node来的方便

**Comment by DoveBoy** [comment]
@710850609 想多用一种方式而已，autojs能达到定时任务的功能吗？

**Comment by DoveBoy** [comment]
autojs官方消息，8.6版本开始将支持nodejs，此issue关闭了
